2023-05-29 03:30:18,979 - [testlogin.py-->line:53] - ERROR: 正确的账号密码:用例执行失败
2023-05-29 03:30:18,979 - [testlogin.py-->line:54] - ERROR: '登录成功' != '实际结果：登录成功!'
- 登录成功
+ 实际结果：登录成功!
Traceback (most recent call last):
  File "D:\PycharmProjects\package1\Testcase\testlogin.py", line 43, in test_login
    self.assertEqual(case["expected"], res)
  File "D:\software\work\anaconda\envs\pytorch\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\software\work\anaconda\envs\pytorch\lib\unittest\case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "D:\software\work\anaconda\envs\pytorch\lib\unittest\case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '登录成功' != '实际结果：登录成功!'
- 登录成功
+ 实际结果：登录成功!

2023-05-29 03:30:19,005 - [testlogin.py-->line:63] - INFO: 错误的账号密码:用例执行成功
