2023-06-03 16:54:06,950 - [testlogin.py-->line:54] - ERROR: 正确的账号密码:用例执行失败
2023-06-03 16:54:06,951 - [testlogin.py-->line:55] - ERROR: '登录成功' != '实际结果：登录成功!'
- 登录成功
+ 实际结果：登录成功!
Traceback (most recent call last):
  File "D:\PycharmProjects\unittest_demo\Testcase\testlogin.py", line 44, in test_login
    self.assertEqual(case["expected"], res)
  File "D:\software\work\anaconda\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\software\work\anaconda\lib\unittest\case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "D:\software\work\anaconda\lib\unittest\case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '登录成功' != '实际结果：登录成功!'
- 登录成功
+ 实际结果：登录成功!

2023-06-03 16:54:06,991 - [testlogin.py-->line:64] - INFO: 错误的账号密码:用例执行成功
